import re
import argparse
import sys

def extract_ram_labels(asm_file, mlb_file):
    # Regex for EQU: "vram_ready  equ $54"
    equ_re = re.compile(r'^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s+equ\s+\$([0-9A-F]+)', re.IGNORECASE)

    ram_lines = []
    in_ram_block = False

    try:
        with open(asm_file, 'r', encoding='utf-8', errors='replace') as f:
            for line in f:
                # Toggle parsing based on block markers
                if "; RAM" in line.upper() and not "; END RAM" in line.upper():
                    in_ram_block = True
                    continue
                if "; END RAM" in line.upper():
                    in_ram_block = False
                    continue

                if in_ram_block:
                    match = equ_re.search(line)
                    if match:
                        label, val_hex = match.groups()
                        val_int = int(val_hex, 16)
                        
                        # Within RAM block, we assume they are Internal RAM or PPU registers
                        if val_int < 0x800:
                            ram_lines.append(f"NesInternalRam:{val_int:X}:{label}:")
                        elif 0x2000 <= val_int <= 0x2007:
                            ram_lines.append(f"NesMemory:{val_int:X}:{label}:")
        
        # Append to the existing MLB file generated by ASM6f
        with open(mlb_file, 'a') as f:
            f.write('\n' + '\n'.join(ram_lines) + '\n')
        
        print(f"Appended {len(ram_lines)} RAM labels from the RAM block to {mlb_file}")

    except FileNotFoundError:
        print(f"Error: {asm_file} not found.")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Extract RAM labels between ; RAM and ; END RAM markers.')
    parser.add_argument('input_asm', help='Input .asm source')
    parser.add_argument('output_mlb', help='Target .mlb file to append to')
    args = parser.parse_args()
    extract_ram_labels(args.input_asm, args.output_mlb)
